# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/qrcode_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
sys.path.insert(0, os.path.abspath(__file__ + "/../../"))
from utils.cv_wrapper import convert_image
from modules.api.qr_handler import QrHandler

class QRScreen(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("QR Screen")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.date_textbox = QtWidgets.QLineEdit()
        self.date_textbox.setObjectName("date_textbox")
        
        self.verticalLayout_2.addWidget(self.date_textbox)
        self.qr_generation_button = QtWidgets.QPushButton()
        self.qr_generation_button.setObjectName("qr_generation_button")
        self.qr_generation_button.setText("Generate QR Code")
        self.qr_generation_button.clicked.connect(self.showQRCode)
        self.verticalLayout_2.addWidget(self.qr_generation_button)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.qrcode_image = QtWidgets.QLabel()
        self.qrcode_image.setAlignment(QtCore.Qt.AlignCenter)
        self.qrcode_image.setObjectName("qrcode_image")
        self.verticalLayout.addWidget(self.qrcode_image)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.setLayout(self.verticalLayout_2)
        # self.setVisible(False)
        # QtCore.QMetaObject.connectSlotsByName(Form)
    def showQRCode(self):
        self.date = self.date_textbox.text()
        print(self.date, self.className, self.lessonId)
        image = QrHandler.generate_qr_endpoint(prefix=str("192.168.1"),classId=self.classId,className=self.className,lessonId=self.lessonId)
        image = convert_image(image)
        self.qrcode_image.setPixmap(image)
    def setData(self, date, classId, className, lessonId):
        self.date_textbox.setText(date)
        self.qrcode_image.clear()
        self.date = date
        self.className = className
        self.lessonId = lessonId
        self.classId = classId
        self.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
